apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        app.kubernetes.io/part-of: "quickcart-demo"
    spec:
      containers:
        - name: order-service
          image: workshop/order-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:3002"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:3003"
            - name: DT_RELEASE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: release
                  key: VERSION
            - name: DT_RELEASE_PRODUCT
              value: "quickcart-demo"
            - name: DT_RELEASE_STAGE
              valueFrom:
                configMapKeyRef:
                  name: release
                  key: STAGE
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
