apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Version (VERSION, newTag) is written by the pipeline; ArgoCD app quickcart-production syncs it.
namespace: quickcart-production

resources:
  - ../../base

configMapGenerator:
  - name: release
    literals:
      - STAGE=production
      - VERSION=initial

images:
  - name: workshop/frontend
    newTag: initial
  - name: workshop/order-service
    newTag: initial
  - name: workshop/payment-service
    newTag: initial
  - name: workshop/inventory-service
    newTag: initial
  - name: workshop/notification-service
    newTag: initial
